fix output

diff --git a/.github/workflows/_github-release.yml b/.github/workflows/_github-release.yml
--- a/.github/workflows/_github-release.yml
+++ b/.github/workflows/_github-release.yml
@@ -60,7 +60,7 @@ jobs:
   check-release-exists:
     runs-on: ubuntu-latest
     outputs:
-      exists: ${{ steps.set_existence.outputs.exists }}
+      exists: ${{ steps.release_check.outputs.exists }}
       tag: ${{ steps.set_tag.outputs.tag }}
 
     steps:
@@ -68,10 +68,11 @@ jobs:
         uses: actions/checkout@v3
       
       # When the GitHub CLI doesn't find a release for the given tag, it will exit 1 with a
-      # message of "release not found".  In our case, it's not an actyual error, just a 
+      # message of "release not found".  In our case, it's not an actual error, just a 
       # confirmation that the release does not already exists so we can go ahead and create it.
+      # The `|| true` makes it so the step does not exit with a non-zero exit code
       - name: Check if release exists for tag
-        id: release_exists
+        id: release_check
         run: |
           output=$((gh release view ${{ env.tag }} --json targetCommitish) 2>&1) || true
           if [[ "$output" == "release not found" ]]
