remove actually pypi release for testing

diff --git a/.github/workflows/_pypi-release.yml b/.github/workflows/_pypi-release.yml
--- a/.github/workflows/_pypi-release.yml
+++ b/.github/workflows/_pypi-release.yml
@@ -28,13 +28,13 @@ on:
         required: true
         type: boolean
     # pass through secrets for both PyPi Test and Prod so they're always there
-    secrets:
-      PYPI_API_TOKEN:
-        description: AWS Access Key ID
-        required: true
-      TEST_PYPI_API_TOKEN:
-        description: Test Pypi api token
-        required: true
+    # secrets:
+    #   PYPI_API_TOKEN:
+    #     description: AWS Access Key ID
+    #     required: true
+    #   TEST_PYPI_API_TOKEN:
+    #     description: Test Pypi api token
+    #     required: true
 
 permissions:
   contents: read
@@ -65,7 +65,7 @@ jobs:
       - name: Set Outputs
       # The above step will just use the latest version if the input version
       # is not found.  So to validate the version we want to release exists
-      # we need to compare teh output version.
+      # we need to compare the output version.
         id: set_existence
         run: |
           if [[ ${{ steps.pypi_info.version }} != ${{ inputs.tag }} ]]
@@ -89,68 +89,68 @@ jobs:
       - name: PyPI Release Exists, Skip
         run: echo A release already exists for this version ${{ inputs.tag }} on Pypi, skipping
 
-  test-pypi-release:
-    runs-on: ubuntu-latest
-    needs: [check-pypi-exists]
-    if: needs.check-pypi-exists.outputs.exists == 'false' && ${{ inputs.testing }} == 'false'
+  # test-pypi-release:
+  #   runs-on: ubuntu-latest
+  #   needs: [check-pypi-exists]
+  #   if: needs.check-pypi-exists.outputs.exists == 'false' && ${{ inputs.testing }} == 'false'
   
-    environment: PypiTest
-    steps:
-      - uses: actions/download-artifact@v3
-        with:
-          name: dist
-          path: 'dist'
+  #   environment: PypiTest
+  #   steps:
+  #     - uses: actions/download-artifact@v3
+  #       with:
+  #         name: dist
+  #         path: 'dist'
 
-      - name: Publish distribution to test PyPI
-        uses: pypa/gh-action-pypi-publish@v1.5
-        with:
-          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
-          repository_url: https://test.pypi.org/legacy/
+  #     - name: Publish distribution to test PyPI
+  #       uses: pypa/gh-action-pypi-publish@v1.5
+  #       with:
+  #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
+  #         repository_url: https://test.pypi.org/legacy/
 
-  prod-pypi-release:
-    runs-on: ubuntu-latest
-    needs: [check-pypi-exists]
-    if: needs.check-pypi-exists.outputs.exists == 'false'  && ${{ inputs.testing }} == 'true'
+  # prod-pypi-release:
+  #   runs-on: ubuntu-latest
+  #   needs: [check-pypi-exists]
+  #   if: needs.check-pypi-exists.outputs.exists == 'false'  && ${{ inputs.testing }} == 'true'
   
-    environment: PypiProd
-    steps:
-      - uses: actions/download-artifact@v3
-        with:
-          name: dist
-          path: 'dist'
+  #   environment: PypiProd
+  #   steps:
+  #     - uses: actions/download-artifact@v3
+  #       with:
+  #         name: dist
+  #         path: 'dist'
 
-      - name: Publish distribution to PyPI
-        if: ${{ inputs.testing }} == 'true'
-        uses: pypa/gh-action-pypi-publish@v1.5
-        with:
-          password: ${{ secrets.PYPI_API_TOKEN }}
+  #     - name: Publish distribution to PyPI
+  #       if: ${{ inputs.testing }} == 'true'
+  #       uses: pypa/gh-action-pypi-publish@v1.5
+  #       with:
+  #         password: ${{ secrets.PYPI_API_TOKEN }}
 
-  validate-pypi-package:
-    runs-on: ubuntu-latest
-    needs: [test-pypi-release, prod-pypi-release]
-    # always run this step because one of the needs are always skipped.
-    if: always()
+  # validate-pypi-package:
+  #   runs-on: ubuntu-latest
+  #   needs: [test-pypi-release, prod-pypi-release]
+  #   # always run this step because one of the needs are always skipped.
+  #   if: always()
 
-    steps:
-      - name: Check PyPI
-        id: pypi_info
-        uses: dbt-labs/actions/py-package-info@v1
-        with:
-          package: ${{ github.event.repository.name }}
-          version: ${{ inputs.version_number }}
-          # test: ${{ inputs.testing }}  TODO: implement in action
+  #   steps:
+  #     - name: Check PyPI
+  #       id: pypi_info
+  #       uses: dbt-labs/actions/py-package-info@v1
+  #       with:
+  #         package: ${{ github.event.repository.name }}
+  #         version: ${{ inputs.version_number }}
+  #         # test: ${{ inputs.testing }}  TODO: implement in action
       
-      - name: Set output
-      # The above step will just use the latest version if the input version
-      # is not found.  So to validate the version we want to release exists
-      # we need to compare teh output version.
-        id: set_existence
-        run: |
-          if [[ ${{ steps.pypi_info.version }} != ${{ inputs.tag }} ]]
-          then
-            echo ${{ inputs.tag }} released to Pypi
-          else
-            echo ${{ inputs.tag }} FAILED to released to Pypi.  Manual intervention required.
-            exit 1
-          fi
+  #     - name: Set output
+  #     # The above step will just use the latest version if the input version
+  #     # is not found.  So to validate the version we want to release exists
+  #     # we need to compare teh output version.
+  #       id: set_existence
+  #       run: |
+  #         if [[ ${{ steps.pypi_info.version }} != ${{ inputs.tag }} ]]
+  #         then
+  #           echo ${{ inputs.tag }} released to Pypi
+  #         else
+  #           echo ${{ inputs.tag }} FAILED to released to Pypi.  Manual intervention required.
+  #           exit 1
+  #         fi
 
