fix ordering

diff --git a/.github/workflows/cut-release-branch.yml b/.github/workflows/cut-release-branch.yml
--- a/.github/workflows/cut-release-branch.yml
+++ b/.github/workflows/cut-release-branch.yml
@@ -310,18 +310,16 @@ jobs:
           git status
           git add .
 
-      # this step will fail on whitespace errors but also correct them
+      # this step will fail on whitespace errors but also correct them, || true ensures it doesn't fail in output
       - name: "Remove Trailing Whitespace Via Pre-commit"
-        continue-on-error: true
         run: |
-          pre-commit run trailing-whitespace --files .bumpversion.cfg
+          pre-commit run trailing-whitespace --files .bumpversion.cfg || true
           git status
 
-      # this step will fail on newline errors but also correct them
+      # this step will fail on newline errors but also correct them, || true ensures it doesn't fail in output
       - name: "Removing Extra Newlines Via Pre-commit"
-        continue-on-error: true
         run: |
-          pre-commit run end-of-file-fixer --files .bumpversion.cfg
+          pre-commit run end-of-file-fixer --files .bumpversion.cfg || true
           git status
 
       - name: "Commit Version Bump to Branch"
@@ -342,7 +340,7 @@ jobs:
 
   open_pr:
     name: "Open PR Against main"
-    needs: ['cleanup_changelog', 'create_temp_branch']
+    needs: ['cleanup_changelog', 'create_temp_branch', 'bump_version']
     runs-on: ubuntu-latest
     outputs:
       pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
