Fix pre-commit failures on PR (#135)
* add cleanup

* cleanup names

* update pre-commit check

* ignore errors

* run in venv

* debug missing package

* fix venv

* try pip installing it

* freeze

* testing

* reorg

* uncomment pr/ne branch

* fix dependencies

* fix inputs

* more updates for docs

* Update .github/workflows/cut-release-branch.yml

diff --git a/.github/workflows/cut-release-branch.yml b/.github/workflows/cut-release-branch.yml
--- a/.github/workflows/cut-release-branch.yml
+++ b/.github/workflows/cut-release-branch.yml
@@ -19,15 +19,20 @@
 # jobs:
 #   changelog:
 #     uses: dbt-labs/actions/.github/workflows/cut-release-branch.yml@main
-#    with:
-#      new_branch_name: 1.2.latest
-#    secrets:
-#      FISHTOWN_BOT_PAT: ${{ secrets.FISHTOWN_BOT_PAT }}
+#     with:
+#       new_branch_name: 1.7.latest
+#       PR_title: "Cleanup main after cutting new 1.7.latest branch"
+#       PR_body: "All adapter PRs will fail CI until the dbt-core PR has been merged due to release version conflicts."
+#     secrets:
+#       FISHTOWN_BOT_PAT: ${{ secrets.FISHTOWN_BOT_PAT }}
+
 
 # TODOs
 # add note to eventually commit changes directly and bypass checks - same as release - when we move to this model run test action after merge
 
 name: Cut new release branch
+run-name: "Cutting New Branch:  ${{ inputs.new_branch_name }}"
+
 
 on:
   workflow_call:
@@ -49,7 +54,7 @@ on:
     outputs:
       PR_number:
         description: "PR number for the opened PR"
-        value: ${{ jobs.cleanup_main.outputs.pr_number }}
+        value: ${{ jobs.open_pr.outputs.pr_number }}
     secrets:
       FISHTOWN_BOT_PAT:
         description: "PAT that allows commits, creating branches and opening PRs"
@@ -67,88 +72,17 @@ env:
 
 jobs:
   prep_work:
-    name: "Audit Inputs"
+    name: "Prep Work"
     runs-on: ubuntu-latest
     steps:
       - name: "[DEBUG] Print Inputs"
         run: |
-          echo "Name of branch to cut:   ${{ inputs.new_branch_name }}"
-
-  cut_new_branch:
-    name: "Cut New Branch ${{ inputs.new_branch_name }}"
-    needs: ['prep_work']
-    runs-on: ubuntu-latest
-
-    steps:
-
-      - name: "Checkout ${{ github.repository }}"
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.FISHTOWN_BOT_PAT }}
-          fetch-depth: 0
-
-      - name: "Ensure New Branch Does Not Exist"
-        id: check_new_branch
-        run: |
-          title="Check New Branch Existence"
-          if git show-ref --quiet ${{ inputs.new_branch_name }}; then
-            message="Branch ${{ inputs.new_branch_name }} already exists.  Exiting."
-            echo "::error $title::$message"
-            exit 1
-          fi
-
-      - name: "Create New Release Branch"
-        run: |
-          git checkout -b ${{ inputs.new_branch_name }}
-
-      - name: "Push up New Branch"
-        run: |
-          #Data for commit
-          user="Github Build Bot"
-          email="buildbot@fishtownanalytics.com"
-          git config user.name "$user"
-          git config user.email "$email"
-          git push --set-upstream origin ${{ inputs.new_branch_name }}
-
-      - name: "[Notification] New branch created"
-        run: |
-          message="New branch ${{ inputs.new_branch_name }} created"
-          echo "::notice title="New branch created": $title::$message"
-
-      - name: "Bump dependencies via script"
-        # This bumps the dependency on dbt-core in the adapters
-        if: ${{ !contains(github.repository, 'dbt-core') }}
-        run: |
-          echo ${{ github.repository }}
-          echo "running update_dependencies script"
-          bash ${GITHUB_WORKSPACE}/.github/scripts/update_dependencies.sh ${{ inputs.new_branch_name }}
-          commit_message="bumping .latest branch variable in update_dependencies.sh to ${{ inputs.new_branch_name }}"
-          git status
-          git add .
-          git commit -m "$commit_message"
-          git push
-
-      - name: "Bump env variable via script"
-        # bumps the RELEASE_BRANCH variable in nightly-release.yml in adapters
-        if: ${{ !contains(github.repository, 'dbt-core') }}
-        run: |
-          file="./.github/scripts/update_release_branch.sh"
-          if test -f "$file"; then
-            echo ${{ github.repository }}
-            echo "running some script yet to be written now"
-            bash $file ${{ inputs.new_branch_name }}
-            commit_message="updating env variable to ${{ inputs.new_branch_name }} in nightly-release.yml"
-            git status
-            git add .
-            git commit -m "$commit_message"
-            git push
-          else
-            echo "no $file seen skipping step"
-          fi
+          echo "new_branch_name:        ${{ inputs.new_branch_name }}"
+          echo "PR_title:               ${{ inputs.PR_title }}"
+          echo "PR_body:                ${{ inputs.PR_body }}"
 
   create_temp_branch:
     name: "Create Temp branch off main"
-    needs: ['cut_new_branch']
     runs-on: ubuntu-latest
     outputs:
       temp_branch_name: ${{ steps.variables.outputs.BRANCH_NAME }}
@@ -231,14 +165,14 @@ jobs:
         # removal fails if no files exist. OK to continue since we're just cleaning up the files.
         continue-on-error: true
         run: |
-          rm .changes/unreleased/*.yaml
+          rm .changes/unreleased/*.yaml || true
 
       - name: "Delete Pre Release Changelogs and YAMLs"
         # removal fails if no files exist. OK to continue since we're just cleaning up the files.
         continue-on-error: true
         run: |
-          rm .changes/${{ steps.semver-current.outputs.base-version }}/*.yaml
-          rm .changes/${{ steps.semver-current.outputs.major }}.${{ steps.semver-current.outputs.minor }}.*.md
+          rm .changes/${{ steps.semver-current.outputs.base-version }}/*.yaml || true
+          rm .changes/${{ steps.semver-current.outputs.major }}.${{ steps.semver-current.outputs.minor }}.*.md || true
 
       - name: "Cleanup CHANGELOG.md"
         run: |
@@ -313,9 +247,51 @@ jobs:
           message="Version on ${{ needs.create_temp_branch.outputs.temp_branch_name }} bumped to ${{ needs.cleanup_changelog.outputs.next-version }}"
           echo "::notice title="Version Bump Completed": $title::$message"
 
+  cleanup:
+    name: "Cleanup Code Quality"
+    needs: ['create_temp_branch', 'bump_version']
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Checkout ${{ github.repository }}"
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ needs.create_temp_branch.outputs.temp_branch_name }}
+          token: ${{ secrets.FISHTOWN_BOT_PAT }}
+
+      - name: "Add Homebrew To PATH"
+        run: |
+          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
+
+      - name: "brew install pre-commit"
+        run: |
+          brew install pre-commit
+      
+      # this step will fail on whitespace errors but also correct them
+      - name: "Cleanup - Remove Trailing Whitespace Via Pre-commit"
+        continue-on-error: true
+        run: |
+          pre-commit run trailing-whitespace --files .bumpversion.cfg CHANGELOG.md .changes/* || true
+
+      # this step will fail on newline errors but also correct them
+      - name: "Cleanup - Remove Extra Newlines Via Pre-commit"
+        continue-on-error: true
+        run: |
+          pre-commit run end-of-file-fixer --files .bumpversion.cfg CHANGELOG.md .changes/* || true
+
+      - name: "Commit Version Bump to Branch"
+        run: |
+          user="Github Build Bot"
+          email="buildbot@fishtownanalytics.com"
+          git config user.name "$user"
+          git config user.email "$email"
+          git status
+          git add .
+          git commit -m "Code quality cleanup"
+          git push
+
   open_pr:
     name: "Open PR Against main"
-    needs: ['cleanup_changelog', 'create_temp_branch', 'bump_version']
+    needs: ['cleanup_changelog', 'create_temp_branch', 'cleanup']
     runs-on: ubuntu-latest
     outputs:
       pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
@@ -363,3 +339,76 @@ jobs:
         run: |
           message="PR opened at ${{ steps.create_pr.outputs.pr_url }}"
           echo "::notice title="Pull Request Opened": $title::$message"
+
+  cut_new_branch:
+    # don't cut the new branch until we're done opening the PR against main
+    name: "Cut New Branch ${{ inputs.new_branch_name }}"
+    needs: [open_pr]
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - name: "Checkout ${{ github.repository }}"
+        uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.FISHTOWN_BOT_PAT }}
+          fetch-depth: 0
+
+      - name: "Ensure New Branch Does Not Exist"
+        id: check_new_branch
+        run: |
+          title="Check New Branch Existence"
+          if git show-ref --quiet ${{ inputs.new_branch_name }}; then
+            message="Branch ${{ inputs.new_branch_name }} already exists.  Exiting."
+            echo "::error $title::$message"
+            exit 1
+          fi
+
+      - name: "Create New Release Branch"
+        run: |
+          git checkout -b ${{ inputs.new_branch_name }}
+
+      - name: "Push up New Branch"
+        run: |
+          #Data for commit
+          user="Github Build Bot"
+          email="buildbot@fishtownanalytics.com"
+          git config user.name "$user"
+          git config user.email "$email"
+          git push --set-upstream origin ${{ inputs.new_branch_name }}
+
+      - name: "[Notification] New branch created"
+        run: |
+          message="New branch ${{ inputs.new_branch_name }} created"
+          echo "::notice title="New branch created": $title::$message"
+
+      - name: "Bump dependencies via script"
+        # This bumps the dependency on dbt-core in the adapters
+        if: ${{ !contains(github.repository, 'dbt-core') }}
+        run: |
+          echo ${{ github.repository }}
+          echo "running update_dependencies script"
+          bash ${GITHUB_WORKSPACE}/.github/scripts/update_dependencies.sh ${{ inputs.new_branch_name }}
+          commit_message="bumping .latest branch variable in update_dependencies.sh to ${{ inputs.new_branch_name }}"
+          git status
+          git add .
+          git commit -m "$commit_message"
+          git push
+
+      - name: "Bump env variable via script"
+        # bumps the RELEASE_BRANCH variable in nightly-release.yml in adapters
+        if: ${{ !contains(github.repository, 'dbt-core') }}
+        run: |
+          file="./.github/scripts/update_release_branch.sh"
+          if test -f "$file"; then
+            echo ${{ github.repository }}
+            echo "running some script yet to be written now"
+            bash $file ${{ inputs.new_branch_name }}
+            commit_message="updating env variable to ${{ inputs.new_branch_name }} in nightly-release.yml"
+            git status
+            git add .
+            git commit -m "$commit_message"
+            git push
+          else
+            echo "no $file seen skipping step"
+          fi
