testing

diff --git a/.github/workflows/cut-release-branch.yml b/.github/workflows/cut-release-branch.yml
--- a/.github/workflows/cut-release-branch.yml
+++ b/.github/workflows/cut-release-branch.yml
@@ -248,14 +248,13 @@ jobs:
         continue-on-error: true
         run: |
           python -m pip freeze
-          python -m pre-commit run trailing-whitespace --files .bumpversion.cfg || true
+          pre-commit run trailing-whitespace --files .bumpversion.cfg
 
       # this step will fail on newline errors but also correct them
       - name: "Cleanup - Remove Extra Newlines Via Pre-commit"
         continue-on-error: true
         run: |
-          source env/bin/activate
-          python -m pre-commit --version
+          python -m pip freeze
           python -m pre-commit run end-of-file-fixer --files .bumpversion.cfg || true
 
       - name: "Commit Version Bump to Branch"
@@ -274,126 +273,126 @@ jobs:
           message="Version on ${{ needs.create_temp_branch.outputs.temp_branch_name }} bumped to ${{ needs.cleanup_changelog.outputs.next-version }}"
           echo "::notice title="Version Bump Completed": $title::$message"
 
-  open_pr:
-    name: "Open PR Against main"
-    needs: ['cleanup_changelog', 'create_temp_branch', 'bump_version']
-    runs-on: ubuntu-latest
-    outputs:
-      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
+  # open_pr:
+  #   name: "Open PR Against main"
+  #   needs: ['cleanup_changelog', 'create_temp_branch', 'bump_version']
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     pr_number: ${{ steps.create_pr.outputs.pull-request-number }}
 
-    steps:
+  #   steps:
 
-      - name: "Checkout ${{ github.repository }}"
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ needs.create_temp_branch.outputs.temp_branch_name }}
-          token: ${{ secrets.FISHTOWN_BOT_PAT }}
+  #     - name: "Checkout ${{ github.repository }}"
+  #       uses: actions/checkout@v3
+  #       with:
+  #         ref: ${{ needs.create_temp_branch.outputs.temp_branch_name }}
+  #         token: ${{ secrets.FISHTOWN_BOT_PAT }}
 
-      - name: "Determine PR Title"
-        id: pr_title
-        run: |
-          echo "pr_title=${{ inputs.PR_title }}" >> $GITHUB_OUTPUT
-          if [${{ inputs.PR_title }} == ""]; then
-            echo "pr_title='Clean up changelogs and bump to version ${{ needs.cleanup_changelog.outputs.next-version }}'" >> $GITHUB_OUTPUT
-          fi
+  #     - name: "Determine PR Title"
+  #       id: pr_title
+  #       run: |
+  #         echo "pr_title=${{ inputs.PR_title }}" >> $GITHUB_OUTPUT
+  #         if [${{ inputs.PR_title }} == ""]; then
+  #           echo "pr_title='Clean up changelogs and bump to version ${{ needs.cleanup_changelog.outputs.next-version }}'" >> $GITHUB_OUTPUT
+  #         fi
 
-      - name: "Determine PR Body"
-        id: pr_body
-        run: |
-          echo "pr_body=${{ inputs.PR_body }}" >> $GITHUB_OUTPUT
-          if [${{ inputs.PR_body }} == ""]; then
-            echo "pr_body='Clean up changelogs and bump to version ${{ needs.cleanup_changelog.outputs.next-version }}'" >> $GITHUB_OUTPUT
-          fi
+  #     - name: "Determine PR Body"
+  #       id: pr_body
+  #       run: |
+  #         echo "pr_body=${{ inputs.PR_body }}" >> $GITHUB_OUTPUT
+  #         if [${{ inputs.PR_body }} == ""]; then
+  #           echo "pr_body='Clean up changelogs and bump to version ${{ needs.cleanup_changelog.outputs.next-version }}'" >> $GITHUB_OUTPUT
+  #         fi
 
-      - name: "Add Branch Details"
-        id: pr_body_branch
-        run: |
-          branch_details="The workflow that generated this PR also created a new branch: ${{ inputs.new_branch_name }}"
-          full_body="${{ steps.pr_body.outputs.pr_body }} $branch_details"
-          echo "pr_full_body=$full_body" >> $GITHUB_OUTPUT
+  #     - name: "Add Branch Details"
+  #       id: pr_body_branch
+  #       run: |
+  #         branch_details="The workflow that generated this PR also created a new branch: ${{ inputs.new_branch_name }}"
+  #         full_body="${{ steps.pr_body.outputs.pr_body }} $branch_details"
+  #         echo "pr_full_body=$full_body" >> $GITHUB_OUTPUT
 
-      - name: "Open Pull Request"
-        id: create_pr
-        run: |
-          pr_url=$(gh pr create -B main -H ${{ needs.create_temp_branch.outputs.temp_branch_name }} -l "Skip Changelog" -t "${{ steps.pr_title.outputs.pr_title }}" -b "${{ steps.pr_body_branch.outputs.pr_full_body }}")
-          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
-        env:
-          GH_TOKEN: ${{ secrets.FISHTOWN_BOT_PAT }}
+  #     - name: "Open Pull Request"
+  #       id: create_pr
+  #       run: |
+  #         pr_url=$(gh pr create -B main -H ${{ needs.create_temp_branch.outputs.temp_branch_name }} -l "Skip Changelog" -t "${{ steps.pr_title.outputs.pr_title }}" -b "${{ steps.pr_body_branch.outputs.pr_full_body }}")
+  #         echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
+  #       env:
+  #         GH_TOKEN: ${{ secrets.FISHTOWN_BOT_PAT }}
 
-      - name: "[Notification] Pull Request Opened"
-        run: |
-          message="PR opened at ${{ steps.create_pr.outputs.pr_url }}"
-          echo "::notice title="Pull Request Opened": $title::$message"
+  #     - name: "[Notification] Pull Request Opened"
+  #       run: |
+  #         message="PR opened at ${{ steps.create_pr.outputs.pr_url }}"
+  #         echo "::notice title="Pull Request Opened": $title::$message"
 
-  cut_new_branch:
-    # don't cut the new branch until we're done openeing the PR against main
-    name: "Cut New Branch ${{ inputs.new_branch_name }}"
-    needs: [open_pr]
-    runs-on: ubuntu-latest
+  # cut_new_branch:
+  #   # don't cut the new branch until we're done openeing the PR against main
+  #   name: "Cut New Branch ${{ inputs.new_branch_name }}"
+  #   needs: [open_pr]
+  #   runs-on: ubuntu-latest
 
-    steps:
+  #   steps:
 
-      - name: "Checkout ${{ github.repository }}"
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.FISHTOWN_BOT_PAT }}
-          fetch-depth: 0
+  #     - name: "Checkout ${{ github.repository }}"
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.FISHTOWN_BOT_PAT }}
+  #         fetch-depth: 0
 
-      - name: "Ensure New Branch Does Not Exist"
-        id: check_new_branch
-        run: |
-          title="Check New Branch Existence"
-          if git show-ref --quiet ${{ inputs.new_branch_name }}; then
-            message="Branch ${{ inputs.new_branch_name }} already exists.  Exiting."
-            echo "::error $title::$message"
-            exit 1
-          fi
+  #     - name: "Ensure New Branch Does Not Exist"
+  #       id: check_new_branch
+  #       run: |
+  #         title="Check New Branch Existence"
+  #         if git show-ref --quiet ${{ inputs.new_branch_name }}; then
+  #           message="Branch ${{ inputs.new_branch_name }} already exists.  Exiting."
+  #           echo "::error $title::$message"
+  #           exit 1
+  #         fi
 
-      - name: "Create New Release Branch"
-        run: |
-          git checkout -b ${{ inputs.new_branch_name }}
+  #     - name: "Create New Release Branch"
+  #       run: |
+  #         git checkout -b ${{ inputs.new_branch_name }}
 
-      - name: "Push up New Branch"
-        run: |
-          #Data for commit
-          user="Github Build Bot"
-          email="buildbot@fishtownanalytics.com"
-          git config user.name "$user"
-          git config user.email "$email"
-          git push --set-upstream origin ${{ inputs.new_branch_name }}
+  #     - name: "Push up New Branch"
+  #       run: |
+  #         #Data for commit
+  #         user="Github Build Bot"
+  #         email="buildbot@fishtownanalytics.com"
+  #         git config user.name "$user"
+  #         git config user.email "$email"
+  #         git push --set-upstream origin ${{ inputs.new_branch_name }}
 
-      - name: "[Notification] New branch created"
-        run: |
-          message="New branch ${{ inputs.new_branch_name }} created"
-          echo "::notice title="New branch created": $title::$message"
+  #     - name: "[Notification] New branch created"
+  #       run: |
+  #         message="New branch ${{ inputs.new_branch_name }} created"
+  #         echo "::notice title="New branch created": $title::$message"
 
-      - name: "Bump dependencies via script"
-        # This bumps the dependency on dbt-core in the adapters
-        if: ${{ !contains(github.repository, 'dbt-core') }}
-        run: |
-          echo ${{ github.repository }}
-          echo "running update_dependencies script"
-          bash ${GITHUB_WORKSPACE}/.github/scripts/update_dependencies.sh ${{ inputs.new_branch_name }}
-          commit_message="bumping .latest branch variable in update_dependencies.sh to ${{ inputs.new_branch_name }}"
-          git status
-          git add .
-          git commit -m "$commit_message"
-          git push
+  #     - name: "Bump dependencies via script"
+  #       # This bumps the dependency on dbt-core in the adapters
+  #       if: ${{ !contains(github.repository, 'dbt-core') }}
+  #       run: |
+  #         echo ${{ github.repository }}
+  #         echo "running update_dependencies script"
+  #         bash ${GITHUB_WORKSPACE}/.github/scripts/update_dependencies.sh ${{ inputs.new_branch_name }}
+  #         commit_message="bumping .latest branch variable in update_dependencies.sh to ${{ inputs.new_branch_name }}"
+  #         git status
+  #         git add .
+  #         git commit -m "$commit_message"
+  #         git push
 
-      - name: "Bump env variable via script"
-        # bumps the RELEASE_BRANCH variable in nightly-release.yml in adapters
-        if: ${{ !contains(github.repository, 'dbt-core') }}
-        run: |
-          file="./.github/scripts/update_release_branch.sh"
-          if test -f "$file"; then
-            echo ${{ github.repository }}
-            echo "running some script yet to be written now"
-            bash $file ${{ inputs.new_branch_name }}
-            commit_message="updating env variable to ${{ inputs.new_branch_name }} in nightly-release.yml"
-            git status
-            git add .
-            git commit -m "$commit_message"
-            git push
-          else
-            echo "no $file seen skipping step"
-          fi
+  #     - name: "Bump env variable via script"
+  #       # bumps the RELEASE_BRANCH variable in nightly-release.yml in adapters
+  #       if: ${{ !contains(github.repository, 'dbt-core') }}
+  #       run: |
+  #         file="./.github/scripts/update_release_branch.sh"
+  #         if test -f "$file"; then
+  #           echo ${{ github.repository }}
+  #           echo "running some script yet to be written now"
+  #           bash $file ${{ inputs.new_branch_name }}
+  #           commit_message="updating env variable to ${{ inputs.new_branch_name }} in nightly-release.yml"
+  #           git status
+  #           git add .
+  #           git commit -m "$commit_message"
+  #           git push
+  #         else
+  #           echo "no $file seen skipping step"
+  #         fi
